### ISSUE TITLE
Register update without `&mut self` results in undefined behavior

### ISSUE THREAD

**Issue by brandenburg** [rust-embedded/register-rs#3]
Hi Andre, 

thanks a lot for all your work making Rust a great platform for embedded development, and in particular thanks for this useful layer (and the `cortex-a` crate) on top of tock-registers! I'd like to build on it. 

I have a question about the design, though: Is it really a good idea to allow destructive updates of (global!) registers without even requiring a mutable reference? Shouldn't `write()` and `set` etc. in the register traits take a `&mut self`? 

(I realize this design choice is inherited from tock-registers, where there may be project-specific considerations that make it a good tradeoff, but this crate has the potential to spread it far and wide, in particular to relatively novice users, so I'm raising the question here. )

Of course it's convenient to just have a const global device with embedded MMIO registers without having to worry about synchronization, especially during early boot, but this is incredibly dangerous.  Wouldn't it be better to stick with the spirit of Rust and let the compiler force the programmer to add proper synchronization (e.g., via `spin::Mutex`)? Arguably, register writes should even be marked as `unsafe`. 

For example, in the context of the bcm2xxx GPIO interface, it's not safe for two cores to be programming different I/O pins at the same time because the pull-up/pull-down sequence has global side effects. Shouldn't the register interface make this explicit — be safe by default? 

As another example, the `cortex-a` crate currently allows (supposedly) *safe* functions to write *arbitrary* values to the `sp` register, which would obviously not end well. So I feel this interface is not well aligned with the core Rust tenet of offering *safe abstractions*  by encapsulating unsafe operations — the register interface just makes something potentially very unsafe *transparently* unsafe, i.e., it's just hiding the problem, rather than offering a safe abstraction. 

Also note that [tock-registers achieves this "danger hiding" by casting a `&` to a `&mut` reference](https://github.com/tock/tock/blob/af68ed93f503ae27b167b1ecf7b943d7659b4133/libraries/tock-register-interface/src/registers.rs#L149-L151). The [Rust documentation for `UnsafeCell`](https://doc.rust-lang.org/nightly/core/cell/struct.UnsafeCell.html) makes it quite clear that this is undefined behavior and a bit of a "no-no":

> If you have a reference `&SomeStruct`, then normally in Rust all fields of `SomeStruct` are immutable. The compiler makes optimizations based on the knowledge that `&T` is not mutably aliased or mutated, and that `&mut T` is unique. `UnsafeCell<T>` is the only core language feature to work around the restriction that `&T` may not be mutated. All other types that allow internal mutability, such as `Cell<T>` and `RefCell<T>`, use `UnsafeCell` to wrap their internal data.  […] The `UnsafeCell<T>` type is the only legal way to obtain aliasable data that is considered mutable. In general, transmuting an `&T` type into an `&mut T` is considered undefined behavior.

So while it seems that tock-registers works (mostly? usually?) ok with the current Rust compiler, future compiler releases might silently and subtly break code that depends on `register-rs`. 

Again, the Tock developers can opt into undefined behavior any way they want, it's their project and not my call to make, but the `register-rs` crate implicitly elevates their choice from "it's fine for Tock" to "it's fine for everyone" who happens to stumble on this crate on crates.io. At the very least, I think there should be a big, fat warning in the description that using this crate means opting into undefined behavior. 

However, since `register-rs` is used in a teaching context in your excellent RPi3 OS dev tutorial, I think it would be even better to prevent clients of the crate from shooting themselves in the foot, at least by default, and I think that means making register writes unsafe and dependent on `&mut self`. Of course that's a legacy-breaking change that may be too costly in the context of Tock, but you mentioned in [Tock#1482](https://github.com/tock/tock/issues/1482#issuecomment-561390502) that you are thinking of (temporarily) forking tock-registers anyway, so why not take the opportunity to fix this, too…

Thanks for your consideration. 

Björn

**Comment by andre-richter** [comment]
Hi Björn,

thanks for the elaborate feedback. You opened a huuuuge topic :)
Let me try to address it from my point of view, and hopefully I'll be able to do it in a coherent manner.

First of all, I agree that we have soundness issues here, at the very least. I would also be open to address them in a breaking change, because last I checked, `register-rs` wasn't adopted very widely yet. The `Oreboot` project uses it, but I'm sure they are open to convincing arguments. However, I think it would be hard to come up with something that really does it better.

Let me first review how `register-rs` came to be.
When I started with (embedded) Rust, people had already resorted to a common pattern for operating on `MMIO` blocks: First, use wrapper types for volatile access to addresses, for example [volatile-register](https://github.com/japaric/volatile-register), and use those to compile a `RegisterBlock` struct, for example [like here](https://github.com/rust-embedded/cortex-m/blob/master/src/peripheral/cbp.rs#L5-L33). While those types safely wrap unsafe volatile reads and writes to raw addresses, in my opinion, the actual point of introducing unsafety is when the user [casts a raw address into one of those `RegisterBlock` structs](https://github.com/rust-embedded/cortex-m/blob/master/src/peripheral/mod.rs#L223-L228).

The common way to work with CPU registers back then was safely wrapping unsafe `asm` calls to access them ([example here](https://github.com/rust-embedded/cortex-m/blob/master/src/register/psp.rs)). This adds a bit of safety, it enforces the register length through Rust's type system, for example.

Often, those two patterns were combined with using constants defined by [bitflags](https://github.com/bitflags/bitflags). So one could use a bitflags constant (that boils down to a primitive like `u32` IINM) and use it as argument for a wrapped MMIO or CPU register operation.
I personally thought that tock-registers did it better, because they used the type system to restrict more explicitly what can be written to a _specific_ register (through the phantom field), but still be zero overhead.
With bitflags, I could accidentally use a wrong bitflags constant that happens to boil down to the correct primivite type. With tock registers, that can't happen so easily.

However, tock registers only supported `MMIO`. I thought it makes sense to have a homogeneous interface for `MMIO` _and_ `CPU` in the same project. That's why I created `register-rs`. It added the missing `CPU` register support. Back then, I did not question other design choices too much because I was just beginning with Rust myself and not understand the intricate issues yet. 

Regarding your question:
> I have a question about the design, though: Is it really a good idea to allow destructive updates of (global!) registers without even requiring a mutable reference? Shouldn't write() and set etc. in the register traits take a &mut self?

I'm not sure it would help much. All the magic added through the traits and implicit casts and what not in the end boils down to a single point where the "real" unsafety is happening:
When those traits evaluate to `ptr::read_volatile()` or `ptr::write_volatile()` calls with an address that was originally supplied by the user.
I could harden the register interface all the way I want, and still side-step it with a single (unsafe) call to  `ptr::write_volatile(CONFLICTING_ADDRESS)`.
So in my opinion, in the end, it still is the user that has to ensure I/O to registers is not happening unsynchronized. I can't prevent users from casting arbitrary integers to pointers and use them for I/O.

> Wouldn't it be better to stick with the spirit of Rust and let the compiler force the programmer to add proper synchronization (e.g., via spin::Mutex)?

The embedded WG is trying to solve this by writing board support crates that already provide peripherals encapsulated in singletons that use sychronization primitives. In my tutorials, I'm wrapping peripherals like the UART into syncrhonization primitives as well (`NullLock` for now, which will be transformed into a real spinlock in an upcoming tutorial). But in the end this still boils down to needing a human that vows that the invariant of "not producing code that writes to the same address from different processing engines (cpu cores) concurrently" is upheld.
It really ties knots into my brain, but I think the conceptual problem is that you cannot(?) easily own a raw address of the system memory map, and therefore you cannot use the compiler to prevent concurrent access to it. That's why Rust's  `ptr::read_volatile()` and `ptr::write_volatile()` are unsafe. People have to use it correctly.

So coming back to back to the original question, I tend to say that transforming the traits to taking an `&mut self` for write operations is not necessarily any safer than ensuring that you only ever instantiate one properly-synchronized struct that accesses the respective memory regions.
That is one of the reason why I [made the instantiation of the drivers `unsafe`](https://github.com/rust-embedded/rust-raspi3-OS-tutorials/blob/master/13_integrated_testing/src/bsp/driver/bcm/bcm2xxx_pl011_uart.rs#L244) in my tutorials.
Instantiate two of them with the same address, and you're borked. This is basically a more abstracted version of "use `write_volatile()` to the same address from two cores concurrently, and you're borked.

One more point to consider: It is not necessarily true that writing to the same address from two CPU cores concurrently will automatically result in undefined behavior. So synchronization is not needed by default in all cases.

For example, I could write to a UART's data register from two cores at the same time in a tight loop, and that is architecturally not a problem in itself as such. The CPU's interconnect would allow to do this, arbitrate with some internal algorithms between the two cores, maybe eventually block execution of the core when the UART's ingress buffer full. The UART output might not make any sense to a user, but technically you can do this.

> As another example, the cortex-a crate currently allows (supposedly) safe functions to write arbitrary values to the sp register, which would obviously not end well.

I agree that operations like that, which can have global side-effects, should probably be unsafe. Evaluation on per-register basis would be needed to decide whether it is safe or not to write arbitrary values to a register. It would be unsafe most of the time, I think.
`cortex-a` was basically a port of the `cortex-m` crate, where those unsafe things are wrapped safely. Maybe the original intention was something like "since this code is conditionally compiled only for the correct `target_arch`, we know this register exists and therefore its safe to execute this line of assembly that accesses it". But yes, one should also consider if writing to the register can have global side-effects and mark `unsafe` respectively.

Coming back to my initial statement: I am open to suggestions/PRs/re-architecture if we can come up with a better concept, so I'd like to hear your thoughts on my ramblings here.

When thinking about a re-design, it makes sense to briefly look at:
-  https://github.com/rust-embedded/wg/pull/387 in the back of your head. But hopefully, this one can get solved on the compiler front sometime in the future.
- https://blog.auxon.io/2019/10/25/type-level-registers
    - I haven't had time yet to work through this yet and understand the added benefit to the current tock implementation, but the claim is made.

Best,
Andre

**Comment by andre-richter** [comment]
Hi Björn,

schließe die Issue mal vorläufig da keine Aktivität in letzter Zeit.
Lass mich gerne wissen wenn es updates von eurer Seite gibt.

**Comment by brandenburg** [comment]
Sorry for just disappearing. As you can tell, life happened and preempted my work on this. I meant to reply with some prototype but never got around to actually looking into it in further detail. I'll let you know should I return to this.
